# Generated by Django 6.0.3 on 2026-03-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.SlugField(max_length=20, unique=True)),
                ('locale_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['language_name'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('msgid', models.TextField()),
                ('msgid_plural', models.TextField(blank=True, default='')),
                ('msgctxt', models.TextField(blank=True, default='')),
                ('msgstr', models.TextField(blank=True, default='')),
                ('msgstr_plural', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('occurrences', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True, default='')),
                ('tcomment', models.TextField(blank=True, default='')),
                ('is_translated', models.BooleanField(default=False)),
                ('is_fuzzy', models.BooleanField(default=False)),
                ('obsolete', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='jawcracker.language')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['language', 'order'], name='jawcracker__languag_adb899_idx'), models.Index(fields=['language', 'is_translated', 'is_fuzzy'], name='jawcracker__languag_587855_idx')],
                'unique_together': {('language', 'hash')},
            },
        ),
    ]
